spring:
  application:
    name: WebGallary
  datasource:
    url: jdbc:postgresql://localhost:5432/kento_official_page
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB

server:
  tomcat:
    remoteip:
      remote-ip-header: "x-forwarded-for"
      protocol-header: "x-forwarded-proto"

management:
  add-application-context-header: false

logging:
  level:
    ROOT: INFO

auth:
  login:
    failCount: 3

app:
  photo:
    photoCountPerPage: 20
    maxFileSizeMb: 5
    outputPath: https://localhost:8080/image/